# Generated by Django 5.1.1 on 2024-09-20 02:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="category",
            field=models.CharField(
                choices=[
                    ("electronics", "Electronics"),
                    ("clothing", "Clothing"),
                    ("home_kitchen", "Home and Kitchen"),
                    ("beauty_personal", "Personal Care"),
                    ("sports_outdoors", "Sports"),
                    ("toys_games", "Toys and Games"),
                    ("automotive", "Automotive"),
                    ("books_media", "Books and Media"),
                    ("health_wellness", "Health"),
                    ("grocery_gourmet", "Grocery"),
                ],
                default="otros",
                max_length=40,
            ),
        ),
    ]
